global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nodejs-backend"
    static_configs:
      - targets: ["16.144.31.60:5000"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["<DB_PUBLIC_IP>:9216"]
